[project]
name = "billee-odesc-configuration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vernonicuhhh", email = "Vernonicuhhh@protonmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "odrive==0.6.5",
]

[project.scripts]
billee-odesc-configuration = "billee_odesc_configuration:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
